ARG ROS_DISTRO=jazzy
FROM osrf/ros:${ROS_DISTRO}-desktop-full
ARG ROS_DISTRO

SHELL ["/bin/bash", "-c"]

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  bash-completion \
  curl            \
  nano            \
  sudo            \
  vim             \
  wget            \
  && rm -rf /var/lib/apt/lists/*

# Development environment dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  clang           \
  clangd          \
  clang-format    \
  clang-tidy      \
  clang-tools     \
  cmake           \
  ccache          \
  gdb             \
  git             \
  git-lfs         \
  lld             \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
  libboost-all-dev    \
  libceres-dev        \
  libeigen3-dev       \
  libgtest-dev        \
  libpcl-dev          \
  libsuitesparse-dev  \
  libyaml-cpp-dev     \
  nlohmann-json3-dev  \
  && rm -rf /var/lib/apt/lists/*

# Robot Operating System (ROS) dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  python3-pip                       \
  python3-venv                      \
  python3-colcon-common-extensions  \
  python3-colcon-mixin              \
  python3-rosdep                    \
  python3-rosinstall-generator      \
  python3-vcstool                   \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
  # ROS 2 middleware implementations
  ros-${ROS_DISTRO}-rmw-cyclonedds-cpp        \
  ros-${ROS_DISTRO}-rmw-desert                \
  ros-${ROS_DISTRO}-rmw-fastrtps-cpp          \
  ros-${ROS_DISTRO}-rmw-fastrtps-dynamic-cpp  \
  ros-${ROS_DISTRO}-rmw-zenoh-cpp             \
  # Teleoperation
  ros-${ROS_DISTRO}-joy                       \
  ros-${ROS_DISTRO}-teleop-twist-joy          \
  ros-${ROS_DISTRO}-teleop-twist-keyboard     \
  ros-${ROS_DISTRO}-joy-linux                 \
  # bags & introspection
  ros-${ROS_DISTRO}-rosbag2-storage           \
  ros-${ROS_DISTRO}-rosbag2-storage-mcap      \
  ros-${ROS_DISTRO}-rqt-bag                   \
  # tf & diagnostics tooling
  ros-${ROS_DISTRO}-rqt-tf-tree               \
  ros-${ROS_DISTRO}-tf2-tools                 \
  ros-${ROS_DISTRO}-diagnostic-aggregator     \
  && rm -rf /var/lib/apt/lists/*